### ISSUE TITLE
Develop System Dashboards

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/grafana-dashboards#3]
# Objective

Develop a Grafana dashboard that integrates with MetricsHub to monitor and report on key system metrics for both Linux and Windows systems. The dashboard will provide real-time insights and historical data analysis to support system administrators in managing system health and performance effectively.

## Data Collection
MetricsHub will be configured to collect Linux and Windows hosts and then reports the following system metrics to Prometheus.

**System Information**: Hostname, OS type, version, uptime, last boot, system time, etc. The connector could be adjusted to report these information.
**CPU**: Metrics `system.cpu.utilization` and `system.cpu.time` (possible states are `user`, `nice`, `system`, `idle` and `io_wait`)
**Memory**: Total, used, free, cached, and available memory. Metrics: `system.memory.usage` and `system.memory.utilization` (possible usagesr are `free`, `used` and `cached`)
**FileSystems**: Usage free and used. Metric: `system.filesystem.usage` (possible states: `free` and `used`).
**Paging**: Swap usage, paging in/out operations.
**Network**: Bandwidth usage, packet transmission statistics, errors, and drops per interface.
**Disks**: Read/write operations, total read/write bytes, disk queue length.
**Services**: Running status, process id.

# Design and Layout
**Overview Section**: Summarize system health with a global status indicator
**Metrics Sections**: Separate sections for CPU, Memory, FileSystems, Paging, Network, Disks, and Services with detailed charts and tables.
**Visualization Types**: Use line charts for time-series data, bar charts for comparative data, (gauges for current state metrics?), and tables for services status.

**Comment by bertysentry** [comment]
Implemented in #16
