### ISSUE TITLE
Reorganize directory structure

### ISSUE THREAD

**Issue by bertysentry** [sentrysoftware/grafana-dashboards#7]
`hardware-sentry` vs `hardware` vs `metricshub`?

**Comment by MarcDouguedroit** [comment]
New directory structure, including new name for the hardware dashboards:

**Hardware**
- Hardware Main (MetricsHub).json
- Hardware Site (MetricsHub).json
- Hardware Host (MetricsHub).json
- Hardware Main (Hardware Sentry).json
- Hardware Site (Hardware Sentry).json
- Hardware Host (Hardware Sentry).json

**System**
- Windows.json
- Linux.json
